### ISSUE TITLE
Inconsistent hover popups

### ISSUE THREAD

**Issue by mg979** [tomv564/LSP#223]
When inside function arguments parentheses, it displays:

![Imgur](https://i.imgur.com/YqPjOb0.png)

When hovering, this instead:

![Imgur](https://i.imgur.com/CWNuZy7.png)

Is it possible to make hover popups display as the first type? Thanks

**Comment by tomv564** [comment]
When we show signatures, LSP is safe to always syntax-highlight the server's response.

In your hover example, the python language server is not marking up the first line with a `language` field, so we don't know if it's code or a paragraph.

This is fixable by changing pyls's hover.py () usage of `Definition.docstring()` here: https://github.com/palantir/python-language-server/blob/3c1f18361179f3a687bdef6209e136a10bbf043f/pyls/plugins/hover.py#L21

Instead of directly returning docstring, that function could return something like 
```python
[ 
{ language: "python", value: make_a_signature_here(definitions[0]) },
definitions[0].docstring(raw=True)
]
```

**Comment by mg979** [comment]
Is there any way I could test this locally? Should I uninstall pyls with pip and reinstall from a modified local copy? Thanks
