### ISSUE TITLE
Project-wide error diagnostics

### ISSUE THREAD

**Issue by chmln** [tomv564/LSP#233]
Hello,

First of all, I wanted to say thank you for this great project and your continuous effort.
It has improved my development experience in Sublime tremendously. 🌞 

I was curious whether there's a way to show all the errors in the project, including files that haven't been opened yet. 

As it stands, the diagnostics panel will stay empty until one opens a file that contains errors. Once you open such a file, the errors will persist in the panel, which is great. But if you were to re-open the same project, the panel would be empty again.

I'm unsure whether this is a part of the LSP protocol or just language-specific extensibility, but it would make for a great dev experience. It would enable one to stop glancing at the compiler CLI to check for errors elsewhere in the project and stay focused in the editor.

P.S. for those who are unable to donate time to contribute to this project, it would be great to be able to donate financially, even in small amounts.

Thanks again 🌞

**Comment by tomv564** [comment]
Hey @chmln, thanks for the kind words - I hadn't thought of donations yet.

I'm in the same boat regarding diagnostics - the panel will look good in sublime, but both web pack and TS are still screaming red errors all over the console.

As a lot of language server development is aimed at VS Code, I try to follow their "only expect diagnostics for open files" model - we could absolutely start showing all received diagnostics instead.

Producing diagnostics for not-yet-opened files is highly language server dependent - which server are you using? 

For example, Microsoft's Typescript Sublime package has a "TSC watch" feature. A typescript-specific addition to LSP could probably implement something similar. Unfortunately this would probably require starting another TSC process instead of reusing the already up-and-running compiler in your language server.

**Comment by chmln** [comment]
> Producing diagnostics for not-yet-opened files is highly language server dependent - which server are you using?

I'm currently using https://github.com/theia-ide/typescript-language-server. It can get really slow at times, but works good enough.

> For example, Microsoft's Typescript Sublime package has a "TSC watch" feature. A typescript-specific addition to LSP could probably implement something similar. Unfortunately this would probably require starting another TSC process instead of reusing the already up-and-running compiler in your language server.

As an optional feature, I think it would be fantastic. As far as running an extra process goes, keeping in mind the resource hogging of VSCode, I wouldn't be concerned at all. The productivity benefits should far outweight the tradeoff.

Would love to contribute in any way to make this happen.

**Comment by tomv564** [comment]
I did some further research and found this VS Code issue to provide a good overview of the options: https://github.com/Microsoft/vscode/issues/13953

VSCode has a workaround based on its support for background tasks and problemMatchers, which are an elegant solution as people tend to run gulp/webpack and different typescript compile wrappers, meaning there is no clear standard.

Should someone implement a package for long-running tasks with output matching, I would gladly help get the output into LSP's diagnostic panel.

There is also a linked issue to the typescript repo: https://github.com/Microsoft/TypeScript/issues/11229
If/when this lands it will allow any typescript language server to support project-wide diagnostics over LSP.

I'm going to close this issue for now, as I see too much work to be done for LSP. If a typescript add-on for this package surfaces, it should be reopened there!
