### ISSUE TITLE
python-language-server hanged Sublime Text by several seconds on file close event

### ISSUE THREAD

**Issue by evandrocoan** [tomv564/LSP#255]
This is the full log:

https://gist.github.com/evandrocoan/98dac8b5944b06c3b6fdc7a11bbc253d

I had closed one view, and my Sublime Text kept frozen until the `python-language-server` answered. Then and only them it does allowed to the view to close and a new view be selected.

The python-language-server must not hang Sublime Text, or LSP should not keep Sublime Text hanged until the Language Server answered.

Some minimal hang is expected as when showing pop-up, but a maximum wait time should be considered to not keep Sublime Text hanging for long periods.

**Comment by tomv564** [comment]
What was python-language-server doing on close?

**Comment by evandrocoan** [comment]
I do understand exactly what you meant by `on close`, but I just had closed one normal/usual file and Sublime Text started hanging on the log hour `19:35:01,043` and started responding again around the hour `19:35:13`

**Comment by tomv564** [comment]
Also looks the same as https://github.com/tomv564/LSP/issues/146

If you had read the logs, you would see it was not didClose on `manual_tests.py` that caused the issue here.
The didChange notification (triggered by a completion request) on `BufferScroll.py` likely caused pyls to hang. 

As the timespan of the freeze is roughly occupied by `pyls`'s linters writing to the logs, I suspect this is causing pyls to hang. 
Why burden your language server with running slow linters, especially if you are not fixing the errors?
If it is the linter causing the slowness, I also don't believe that should stop pyls from responding to other requests.

**Comment by evandrocoan** [comment]
> The didChange notification (triggered by a completion request) on BufferScroll.py likely caused pyls to hang.

BufferScrool do not do completions requests.
