### ISSUE TITLE
Function signature overlay changes after a second

### ISSUE THREAD

**Issue by JeanMertz** [tomv564/LSP#318]
I'm using the [sourcegraph/go-langserver](https://github.com/sourcegraph/go-langserver) as the language server for my Golang completion needs.

I use this plugin as the client.

Here's the LSP config:

```json
{
  "clients": {
    "golsp":
    {
      "command": ["go-langserver", "-gocodecompletion=true"],
      "scopes": ["source.go"],
      "syntaxes": ["Packages/Go/Go.sublime-syntax"],
      "languageId": "go"
    },
  },
}
```

Things work as expected, however, whenever I complete a function, it (~sometimes~, I'm now pretty confident it always happens, but only the first time I hover over a function name after completing it, or manually typing it) briefly shows the correct popup, and then suddenly switches to a different popup style.

This is what I get after I hit `<tab>` and hover over `Info`:

<img width="821" alt="screen shot 2018-05-06 at 15 57 45" src="https://user-images.githubusercontent.com/383250/39674078-05b6a350-5147-11e8-90fd-9dbc1fdd76e3.png">

However, ~_sometimes_~ after only half a second or so, the popup switches to this one (without me moving the mouse, or doing anything else):

<img width="627" alt="screen shot 2018-05-06 at 15 58 07" src="https://user-images.githubusercontent.com/383250/39674083-17b71f6c-5147-11e8-97d6-f6ce3a2200b1.png">

It only happens the first time I hover over `Info`, if I hover over it a second or third time, things work as expected and the first popup stays open, and the second one never shows again.

Interestingly enough, If I hit `tab` twice, or three times, _before_ hovering over `Info`, the mouse moves to the different highlight areas, but the second popup still shows at the first hover over `Info`, and as you can see, the bold part of the popover does not match the actual selection in the editor:

<img width="622" alt="screen shot 2018-05-06 at 16 05 21" src="https://user-images.githubusercontent.com/383250/39674127-909324d0-5147-11e8-8edd-58dba13a2e14.png">

<img width="627" alt="screen shot 2018-05-06 at 16 05 34" src="https://user-images.githubusercontent.com/383250/39674129-96a4f678-5147-11e8-8a11-50957accb2fb.png">

I'm unsure what causes this, but I've re-installed my Sublime Text 3 installation and only installed this package, so I'm pretty sure it's either this package, the language server itself, or the default Sublime Text 3 behaviour that's messing with things.

* OS and language server: macOS, go-langserver
* How you installed LSP: Package Control
* Log (trimmed)

starting with nothing, then typing `logger.Info<tab>` and hovering over `Info` returns these logs:

```
LSP:  --> textDocument/didChange
LSP:  --> textDocument/completion
LSP:  --> textDocument/didChange
LSP:  --> textDocument/completion
LSP:  --> textDocument/didChange
LSP:  --> textDocument/signatureHelp
LSP:  --> textDocument/hover
```

There's only one `hover` command, related to me mousing over `Info`, even though the first popup is still replaced with the second one as shown in the screenshot above after ~half a second.

**Comment by rwols** [comment]
There are two different pop-up functions happening.

There's the "hover" popup. This activates when you hover over an entity with your mouse. It may be distinguished by the three additional commands *Definition*, *References*, *Rename* in it.

Then there's the "signature help" popup. This activates when to the left of your cursor there are certain trigger characters that may trigger it. (in this case, I'm guessing `(` is a trigger character, because it's the start of a function call). The purpose of the "signature help" popup is to help you with the currently active signature of the function-call that you're writing, possibly providing documentation about the current parameter.

From what I can gather from the logs, `signatureHelp` was sent immediately after `completion`. I'm guessing that the go language server takes a while to figure out what it should return. In the meantime, you hover your mouse over the function and LSP then requests `hover` from the go language server, apparently returning almost immediately a result. After this, the go language server returns its response for the `signatureHelp` request and LSP updates the popup with new info.

I don't truly understand the problem, because would *not* hovering over the function solve your problem?

Do you have some setting enabled, wether in ST or in macOS, where the mouse follows the cursor?

**Comment by rwols** [comment]
> Is there any way to disable the function signature popup?

No, but it would not be hard to implement. One would have to adjust `SignatureHelpListener.initialize` in `plugin/signature_help.py`, add a setting in `plugin/core/settings.py`, add the same setting to `LSP.sublime-settings`, and document it `docs/index.md`.

**Comment by JeanMertz** [comment]
Thanks for the pointers 👍 

I did some tests, but there is definitely value in having the function signature show up once I tab-complete a function.

I now understand better what it is that was causing me problems here.

I completed a function, no function signature shows up (because of the long delay), so I kind of created muscle-memory of directly hovering over the function to show the signature in the regular "hover" panel. Then, once the server responses with the function signature details, LSP would swap the hover panel for the new function signature panel.

Clearly, the best solution here is to try and get the server to respond faster, instead of disabling the function signature response and having to hover over the function name to see more details.

I'll close this issue, and will see if there's something to be done on the server-side performance for this specific request.
