### ISSUE TITLE
Show line of reference in panel

### ISSUE THREAD

**Issue by FichteFoll** [tomv564/LSP#412]
### Suggestion:

When displaying references, it would be nice if the line was also copied into the panel at the bottom. Maybe with a configurable number of surrounding lines for better context and the actual usage highlighted with an outline box.

Would also be helpful in remembering whose references you are actually seeing.

I'm using pyls, FWIW.

**Comment by predragnikolic** [comment]
Something like this?

![2018-09-14-144330_683x617_scrot](https://user-images.githubusercontent.com/22029477/45550909-9b659e00-b82c-11e8-9c30-f49dcc0b43a1.png)

**Comment by FichteFoll** [comment]
Yes.

**Comment by predragnikolic** [comment]
Ok I got stuck hahaha.
I was working on [this](https://github.com/predragnikolic/LSP/commit/dd01c35f9d649fe80e39a5eb30a99d25e2810318) and there are two things left:
* update the syntax file. (don't know this)
* figure out the regex for [`result_file_regex` and `result_line_regex`](https://github.com/predragnikolic/LSP/blob/dd01c35f9d649fe80e39a5eb30a99d25e2810318/plugin/references.py#L28-L29).  (don't know this eater)

I tried to see how the diagnostics panel handle this, because now the references panel look looks similar to the diagnostic, but I can't figure it out. 

If there is anyone who knows how to solve this, please leave a comment.

**Comment by predragnikolic** [comment]
It is done :)
![2018-09-17-132740_683x768_scrot](https://user-images.githubusercontent.com/22029477/45620539-96e3f400-ba7d-11e8-8604-2d11afc4e21c.png)

You can try it out if you want by cloning this [here](https://github.com/predragnikolic/LSP/tree/change-look-of-references). Any feedback, suggestions would be appreciated. 
I will make a PR if everybody is happy with it, but I find it definitely more useful now.

**Comment by rwols** [comment]
This looks very useful, @predragnikolic.
