### ISSUE TITLE
Cannot find module from conda virtual env

### ISSUE THREAD

**Issue by dridk** [tomv564/LSP#434]
### Bug:
* Linux and pyls
* How you installed LSP : Package Control 
* Minimal reproduction steps

I cannot detect python libraries installed locally with conda. 

### Create a conda virtual environement and install pandas 
 
        conda create -n test 
        source activate test 
        conda install pandas

### From sublime text, activate pyls and edit configuration as bellow : 

```
{
	"clients":
	{
		"pyls":
		{
			"command":
			[
				"/home/sacha/Bioinfo/miniconda3/envs/test/bin/python","-m","pyls"
			],
			"enabled": true,
			"syntaxes":
			[
				"Packages/Python/Python.sublime-syntax"
			]
		}
	}
}
```

I get the following error : 

![image](https://user-images.githubusercontent.com/1911063/46983189-bf442a00-d0df-11e8-904b-5274292b45b4.png)

**Comment by tomv564** [comment]
Hi, it looks like an issue specific to configuring the mypy plugin to pyls to your development environment. (You did mean to use mypy? Otherwise you could uninstall or disable it)

You can either:
* Help the pandas project generating stubs and upload them to typeshed
* Disable stub lookups for pandas or all libraries in `mypy.ini`: 
https://mypy.readthedocs.io/en/latest/config_file.html

**Comment by tomv564** [comment]
Closing this now as the issue doesn't appear to be directly related to LSP package. 
The mypy pyls plugin will soon update its follow_imports setting, which might change this behaviour as well.
