### ISSUE TITLE
Sometimes `didChange` appears after `completion`

### ISSUE THREAD

**Issue by PMunch** [tomv564/LSP#451]
I'm creating a new language server and started using Sublime to test my implementation. I noticed that sometimes Sublime will send a `textDocument/completion` request before it sends the `textDocument/didChange` notification that contains the position in the completion. This means that the position in the `completion` requests points to either an illegal position, or on something else than what it's supposed to which results in really strange completions.

**Comment by tomv564** [comment]
LSP tries to prevent this by calling 
```
global_events.publish("view.on_purge_changes", self.view)
```
which should synchronously send the didChange before returning to request completions.

In normal operations, edits are debounced before a didChange is invoked. Because timeouts are involved it's possible that here a didChange notification is written right after a completion.

I agree the result is a catastrophe for the language server.
Any chance you can share more details how this can be triggered?

**Comment by tomv564** [comment]
Within a single completion request, the same thread writes a didChange to the server before completions are requested. 

I believe it's possible that typing after a completion has been triggered will result in a `didChange` - `completions` - `didChange` sequence, but we will need more details to learn what is going wrong. Especially @PMunch who had his own server could probably catch an occurrence easily - please follow up if you can help!

For now, closing by lack of reports.
