### ISSUE TITLE
Why there are scroll bars on the houver pop up with so much screen available for it?

### ISSUE THREAD

**Issue by evandrocoan** [tomv564/LSP#486]
When reporting the issue: 
1. https://github.com/palantir/python-language-server/issues/464 Go to definition has a annoying behavior sometimes

I noticed this:
![fsg](https://user-images.githubusercontent.com/5332158/50059436-eb2a6d00-016d-11e9-9cfb-e865ea3e1139.gif)

Are the scroll bars being put there by LSP or Sublime Text? If by LSP, would be nice a setting to extend their limits/maximum sizes. They do not seem big enough.

**Comment by evandrocoan** [comment]
I set 1200, now it show like this:
![image](https://user-images.githubusercontent.com/5332158/50386128-486f7280-06c8-11e9-8d9f-d6b5d5abd89c.png)

So, I would need to hard code this value? Could this be a setting or detected by screen size?
```python
File: Data/Packages/LSP/plugin/hover.py
147:     def show_hover(self, point, contents):
148:         mdpopups.show_popup(
149:             self.view,
150:             contents,
151:             css=popup_css,
152:             md=False,
153:             flags=sublime.HIDE_ON_MOUSE_MOVE_AWAY,
154:             location=point,
155:             wrapper_class=popup_class,
156:             max_width=1200,
157:             on_navigate=lambda href: self.on_hover_navigate(href, point))
158: 
```

**Comment by evandrocoan** [comment]
1. If we do not specify a value `mdpopups` defaults to 320.
1. If `mdpopups` do not specify a value, the `sublime`'s view module also defaults to 320.

This could be either an enhancement for `sublime`'s view module or `mdpopups` dependency:
1. If we specify a wildcard value as -1 or 0, they should adjust the maximum width automatically.
1. Or we just set it to a big value like 2000 and `sublime`'s view module or `mdpopups` dependency should automatically not show it bigger than the user's screen maximum width, i.e., outside the screen.

**Comment by tomv564** [comment]
Thanks for the in-depth investigations!

Normally the popup is vertically sized to accommodate the 3 lines of text. The horizontal scrollbar 
seems to be missing from this vertical size calculation. If it's not our CSS causing this, then we should report this to Sublime Core issues?

As for configuring `max_width`, I feel 800px is a reasonable maximum for pleasant reading of paragraphs of text. The real challenge is that long non-breakable URL :/

Open to suggestions for actions for LSP!

**Comment by cixtor** [comment]
Hello, something I still don’t understand is, how is `max_height` calculated?

With every LSP update, I modify the code to set `max_width=500` because I personally don’t like to read long lines of text, and also it kind of matches the size of the comment block in the code _(when using an 80 character limit)_. I understand that shortening the width of the popup increases the vertical of the container, but even setting `max_height=600` the box still leaves a few points of margin at the bottom.

![a](https://user-images.githubusercontent.com/1933999/55111519-d2e4bb00-5097-11e9-80a8-36ec0a4e1309.gif)

In the GIF above, you can see two functions with comments, the first one has 805 characters, and the second has 207. However, for reasons that I don’t understand, the popup for the big comment is visible larger than the popup with the smaller comment. After setting `max_height` I expect the big one to have a scroll bar, but not the second one.

I ended up adding borders to all the elements in the popup via [plugin/core/popups.py](https://github.com/tomv564/LSP/blob/6d64e31fed6a008473ed3f692c85cb94e45be17e/plugin/core/popups.py) but the CSS in SublimeText is quite limited, so I couldn’t pin-point the correct place for the fix.

Anyway, thank you for all the work you’ve put into this project @tomv564.

**Comment by tomv564** [comment]
https://github.com/SublimeTextIssues/Core/issues/2711 is also a likely explanation. Two things we can try:

* Manually wrap long lines at X chars (say 80)
* Avoid having long content in `span` tags.

**Comment by evandrocoan** [comment]
May be try to use something else other than `<span>` tags?

**Comment by FHTheron** [comment]
Being able to control the scroll position in the signature help would be an alternative to making it larger. The main issue with only seeing two lines is that each time you move to a new parameter the popup updates and scrolls back to the top.

For now, the following gives me something that is more useful for me:
```diff
diff --git a/plugin/signature_help.py b/plugin/signature_help.py
index e058a03..1d21407 100644
--- a/plugin/signature_help.py
+++ b/plugin/signature_help.py
@@ -40,7 +40,7 @@ class ColorSchemeScopeRenderer(object):
         color = self._scope_styles[scope]["color"]
         additional_styles = 'font-weight: bold; text-decoration: underline;' if emphasize else ''
         content = html.escape(content, quote=False) if escape else content
-        return '<span style="color: {};{}">{}</span>'.format(color, additional_styles, content)
+        return '<br><span style="color: {};{}">{}</span>'.format(color, additional_styles, content)
 
 
 class SignatureHelpListener(sublime_plugin.ViewEventListener):
@@ -129,7 +129,7 @@ class SignatureHelpListener(sublime_plugin.ViewEventListener):
                             content,
                             css=popup_css,
                             md=True,
-                            flags=sublime.HIDE_ON_MOUSE_MOVE_AWAY,
+                            flags=0,
                             location=point,
                             wrapper_class=popup_class,
                             max_width=800,
```
