### ISSUE TITLE
"auto_show_diagnostics_panel": false not working

### ISSUE THREAD

**Issue by jhrcook** [tomv564/LSP#500]
Hello,

The diagnostics panel keeps popping up even though I have added `"auto_show_diagnostics_panel': false` to the settings. I have pasted my settings for the `rlang` server in "LSP.sublime-settings - User" below:

```
{
	"clients":
	{
		"rlang":
		{
			"complete_all_chars": true,
			"completion_hint_type": "detail",
			"enabled": true,
			"languageId": "r",
			"scopes":
			[
				"source.r"
			],
			"show_view_status": true,
			"auto_show_diagnostics_panel": false,
			"syntaxes":
			[
				"Packages/R/R.sublime-syntax"
			]
		}
	}
}
```

I did have SublimeLinter + lintr installed, but removed them and the panel keeps popping up randomly. I install LSP through Package Control and download `rlang` from CRAN to my R library. The autocompletion and other LSP services work fine. Disabling the server either through the Command Palette or manually switching `"enabled": false` stops the panel from popping up, so I am convinced it is a problem in LSP.

Thank you for any help with this problem,
Josh Cook

**Comment by jhrcook** [comment]
Thank you @predragnikolic! So I know for the future, why did moving the same instructions to "clients" work?

Thank you,
Josh Cook

**Comment by predragnikolic** [comment]
Of course,

If you open `LSP` preferences. 
The left-hand pane contains all of the default settings, along with a description of each. 
The right-hand pane is where customization can be saved. 

The reason it didn't work for you, is because you placed some of the settings in the wrong place (`"clients"` in your case above). If you see the [description](https://github.com/tomv564/LSP/blob/93da20f2763b7c584c9b8244d64de9ae1ce97988/LSP.sublime-settings#L8-L34) for the `"clients"` you would see what are valid values that the `"clients"` settings accept.

Feel free to close this issue if your issue is gone.

**Comment by jhrcook** [comment]
That makes sense, thank you for clearing this up for me. Just made my weekend!

Thank you,
Josh Cook
