### ISSUE TITLE
Intelephense document symbols isn't working

### ISSUE THREAD

**Issue by carlevison** [tomv564/LSP#519]
When triggering the document symbols command no properties or methods are displayed.

* OSX 10.14 Intelephense v1.0.2
* Package Control
* Trigger LSP ```lsp_document_symbols```
* Log:

```
Traceback (most recent call last):
  File "/Users/carlos/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/symbols.py", line 70, in on_symbol_selected
    range = selected_symbol['location']['range']
KeyError: 'location'
```

**Comment by rwols** [comment]
So this bug is somewhat in the same style as #517 I think, where this plugin is not up-to-date with the latest protocol changes. In this case, the result of a `textDocument/documentSymbol` request can be either a list of `DocumentSymbol` (which we *don't* support) or `SymbolInformation` (which we *do* support), or `None`. We should fix this accordingly.

**Comment by carlevison** [comment]
@rwols Thank you for the information and for the great work you're doing with this plugin :)

**Comment by rwols** [comment]
Should be fixed by https://github.com/tomv564/LSP/pull/524.
