### ISSUE TITLE
Duplicate information in the completion popup

### ISSUE THREAD

**Issue by RUSshy** [tomv564/LSP#618]
OS: Windows 10 - x64
Sublime Text: v3.2.1
LSP: 0.8.4 (From Package Manager)

I am using it with the D plugin: https://github.com/d-language-server/dls

Aa you can see in the screenshot, for the fields data is duplicated

![aSMd1TIArG](https://user-images.githubusercontent.com/18348637/59605026-10dd0280-910e-11e9-9211-60dd12d1db6b.png)

**Comment by rwols** [comment]
The information that is right-aligned in the completion widget is determined (by default) as follows:

1) If the LSP CompletionItem contains `detail`, use that.
2) Otherwise, if the LSP CompletionItem contains `hint`, use that.
3) Otherwise, don't display anything.

It looks like the D language server inserts `<type of variable> <name of variable>` in the `detail` field? I'm not a D user. You might want to open an issue about this on their repository.

What you can also do is change the default completion_hint_type setting to `kind`:
```
  // Controls which hints the completion panel displays
  // "auto": completion details if available or kind otherwise
  // "detail": completion details if available
  // "kind": completion kind if available
  // "none": completion item label only
  "completion_hint_type": "auto",
```

**Comment by RUSshy** [comment]
That setting fixed my issue thanks :)
