### ISSUE TITLE
auto_show_diagnostics_panel only on save

### ISSUE THREAD

**Issue by arxeiss** [tomv564/LSP#635]
* OS and language server: **Ubuntu**
* How you installed LSP: **Package Control**

I installed LSP with Intelephense and it works great! Thank you so much for this connector. However when I type and stop, diagnostics panel shows up, and when I type again it hides. And all over again, which is little annoying.

I know I can disable it, but this is not what I prefer. I would like to have an option like `auto_show_diagnostics_panel: 'on-save'` which will trigger this panel to show only when I press CTRL+S.

Would it be possible to add this option? Thank you

**Comment by cheoAlejo** [comment]
I would go further and say that the linting only gets done "on  save". Sublime linter has an option to lint only when the file is saved, so you can focus on writing code and only be warned about errors when you save the file.

**Comment by tomv564** [comment]
@cheoAlejo - the linting/error checking work is not something requested by LSP - language servers are free to send diagnostics whenever they want to, and many default on error-checking unsaved content.

@arxeiss - I think we can improve the showing/hiding behaviour but I'd like to know what LSP is receiving in the case. Can you tell me if the panel hides automatically because you fixed the errors, or does the panel temporarily disappear when you resume typing and then re-appear because the errors are still there?

**Comment by tomv564** [comment]
This request already exists as #381, please follow that issue instead!
