### ISSUE TITLE
feature request: goto declaration in hover

### ISSUE THREAD

**Issue by maddanio** [tomv564/LSP#636]
when i click definition in the hover it goes to the implementation. sublime in turn with "go to definition" actually goes to the declaration. can we have both in the hover, as declaration/implemntation maybe?

**Comment by rwols** [comment]
Since version 3.6 of the LSP protocol a language server can advertise both "goto definition" and "goto implementation". I'm not sure if the language server that you're using (CCLS? clangd?) actually provides that capability.

Currently we only do `textDocument/definition`.

You can check wether the server supports `textDocument/implementation` (as well as `textDocument/definition`) by inspecting the `capabilities` property of the `Session` object.

We (this plugin) should also advertise that we can support `textDocument/implementation` by adding an entry to the `initialize` request: https://github.com/tomv564/LSP/blob/master/plugin/core/sessions.py#L137

The capabilities are assigned to the session here: https://github.com/tomv564/LSP/blob/master/plugin/core/sessions.py#L186

When we have determined that the server supports `textDocument/implementation`, we'll have to write the glue between LSP and ST. Writing that glue would probably look very similar to the glue for `textDocument/definition`, which is here: https://github.com/tomv564/LSP/blob/master/plugin/definition.py

**Comment by maddanio** [comment]
Ok, one data point: goto definition actually goes to the implementation for me (ccls)

**Comment by rwols** [comment]
I see. I see now there's also a "goto declaration": https://microsoft.github.io/language-server-protocol/specification#textDocument_declaration

It seems to be present in clangd: https://github.com/llvm/llvm-project/blob/1ca2ee4dc11437b1b2f183190b1bf52d9f0e1151/clang-tools-extra/clangd/ClangdLSPServer.cpp#L1006

Let me put here the list of un-implemented "goto XXX" requests for reference:

- textDocument/declaration (v.3.14.0)
- textDocument/typeDefinition (v3.6.0)
- textDocument/implementation (v3.6.0)

**Comment by tomv564** [comment]
I checked ccls, they support all of the "goto XXX" flavours. I think the best solution is for LSP to catch up!

If ccls's interpretation of the word "definition" is not correct you could take it up with them :)
