### ISSUE TITLE
[Feature request] toggle language servers

### ISSUE THREAD

**Issue by randy3k** [tomv564/LSP#69]
It should be nice to be able to enable/disable specific servers.

**Comment by tomv564** [comment]
Agree, this is a must-have as currently LSP is an always-on setup.
What solutions do you think will work best?
* A command that writes a project-specific setting to disable a language server by name?
* The ability to configure a language server at the project level *instead of* at the package level?

**Comment by randy3k** [comment]
I guess there should be an option to disable a server globally via `LSP.sublime-settings` and also a project specific setting to enable/disable certain servers.

**Comment by tomv564** [comment]
The configuration to support this was merged in #74.
There is some discussion about what the default language server configuration should look like in #76.
It would be nice to say *Enable* or *Disable* instead of Toggle, but unsure how specific the name of a command in the quick panel can be? (The "Restart Servers" command should perhaps also say "LSP - Restart pyls" for example)

**Comment by randy3k** [comment]
Enabling ane disabling the servers do make more sense. I also found "Restart Servers" confusing, does it restart all running servers or just restart the server of the current window!?

May be this?

- LSP: Enable Server Globally
- LSP: Disable Server Globally
- LSP: Enable Server for Current Project
- LSP: Disable Server for Current Project
- LSP: Restart Server of Current Window

I also not that you are loading the project settings from the key `LSP` of `view.settings`. I think it should be `window.project_data`.

**Comment by tomv564** [comment]
Yes, those look like good suggestions, including using `window.project_data`, thanks!
I've started some work on making these commands part of a first-time setup flow.

**Comment by tomv564** [comment]
#119 added Enable/Disable language server Globally / in Project.
Please let me know if it doesn't work as expected!
