### ISSUE TITLE
Flickering auto-complete panel

### ISSUE THREAD

**Issue by genericptr** [tomv564/LSP#729]
I've installed LSP and tested on some PHP code (the only server I managed to install correctly). The first bug I'm seeing is the auto-complete panel flicker when I type (the panel is hides and re-shows very fast producing a flicker).

Is this a known bug or something I can fix?

**Comment by rwols** [comment]
This is "intended behavior", to the extent that the server is signaling to the plugin that the completion list is incomplete. The plugin responds to that by re-requesting completions as soon as you have typed another character.

The API of SublimeText does not actually have such support for incomplete completions and the re-requesting logic, so a workaround was implemented for this LSP feature.

The effect is smooth on macOS, but can be especially noticable on Linux. I don't personally mind the flickering, because the eventual quality of completions is much higher with this feature.

The best fix for this flickering would be for the SublimeText API to allow us to notify that a completion list is incomplete, and then letting SublimeText decide when to re-query for completions.

The logic for handling incomplete completions is mostly here: https://github.com/tomv564/LSP/blob/be60102fdf8b72de85fe1088eafbd248516ef6f9/plugin/completion.py#L164-L168

**Comment by genericptr** [comment]
I guess we need to file a bug report with Sublime Text then? I'm on macOS also but the flicker is pretty annoying in my opinion so It would be nice if it could be fixed.

**Comment by rwols** [comment]
It's not a really a bug of SublimeText. It's just that this plugin works around the limited API to implement an LSP feature.

**Comment by genericptr** [comment]
It sounds like there is a delay when communicating with the server and ST closes the panel instead of keeping it open or blocking? I may put a feature request in on the ST forums and reference this issue. Thanks.

**Comment by tomv564** [comment]
Can you try setting the `only_show_lsp_completions` to True? Does that improve the flickering?

**Comment by genericptr** [comment]
Setting only_show_lsp_completions to true doesn't help. The panel always hides itself after every character change. According to the previous poster this is just a problem with ST.

**Comment by genericptr** [comment]
I've reported this to ST to see if they have any interest in it. Good Language Server Support is needed for ST going forward if they want to survive against VSCode.

https://forum.sublimetext.com/t/lsp-plugin-completion-flickers/46660

**Comment by genericptr** [comment]
According to my post ST team is already aware of this bug and fixed it in Sublime Merge already so it may get fixed in ST eventually although they don't tend to put out very frequent updates.

**Comment by rwols** [comment]
I'm not good at reading between the lines, but in case you don't know, @deathaxe is not part of the development team of ST. Although he is a very active member of the community and great programmer.

Other people have already asked for better LSP integration on the forums:

https://forum.sublimetext.com/t/range-for-on-query-completions-and-callback-auto-complete/42780
https://forum.sublimetext.com/t/do-you-have-plans-to-add-native-lsp-support-in-next-releases/45134
(and much more threads that are alike)
