### ISSUE TITLE
Disable LSP diagnostics completely

### ISSUE THREAD

**Issue by dvcrn** [tomv564/LSP#762]
I'm looking for a way to completely turn off LSP diagnostics. I am currently using SublimeLinter as my centralized linting framework but it often conflicts or gets confusing when LSP pushes diagnostics as well. My specific case is with `gopls` 

I tried the diagnostic settings:

```
    "auto_show_diagnostics_panel": false,
    "show_diagnostics_count_in_view_status": false,
    "show_diagnostics_in_view_status": false,
    "show_diagnostics_phantoms": false,
    "show_diagnostics_severity_level": 0,
    "diagnostics_highlight_style": "",
    "document_highlight_style": "",
    "diagnostics_gutter_marker": "",
```

but the hover diagnostics and underlining of errors still happens from the LSP plugin. The only way to completely kill it is by adding `hover` to the `disabled_capabilities` list but I'd like to keep the hovers, I just want to handle the diagnostics part differently. 

Is this doable?

**Comment by tomv564** [comment]
It's probably possible but makes little sense for most users as they are not running two syntax checkers simultaneously on their code. Even if we hide the diagnostics UI, the server is still doing all the work so I'd try to look there instead (or switch from SublimeLinter)

**Comment by dndrsn** [comment]
For anyone else arriving here, see https://github.com/sublimelsp/LSP/pull/800/files for context on why     show_diagnostics_severity_level does not apply to the view.  

Perhaps separating it into two settings, one for view and one for panel + sidebar... or add a setting to allow applying the setting to the view as well could be more flexible.

**Comment by peterkos** [comment]
A potential use case is for using `RLS` (Rust's LSP implementation) alongside [rust-enhanced](https://github.com/rust-lang/rust-enhanced/). Currently LSP is lacking a lot of diagnostic customization (e.g., solid underline) that rust-enhanced _does_ have. However, since LSP cannot disable diagnostic information, I can't enable both the `rust-enhanced` syntax checker (which is very featured) and LSP (which offers amazing autocomplete).

**Comment by sterliakov** [comment]
I'm looking for any good solution to this issue for a very long time. My motivation is different from OP's, though: I really, really do want to stop any squiggle underlines, warning signs and other distracting stuff from appearing on my screen, and the whole bunch of linters I use live in pre-commit, I don't want Sublime to duplicate this information. I'll go to terminal and see all the errors before committing anyway, and they are 90% moot while I'm still editing code. It's even more important when my LSP is different from my linter (e.g. basedpyright as an LSP provider, but mypy as a type checker).

I already spent a whole lot of time disabling all diagnostic options in all the installed LSP packages, but have never managed to reach complete silence. I still have to disable new rules and rules I somehow missed earlier regularly. I'd **really** appreciate a single LSP setting to disable all diagnostics globally for all servers.

**Comment by jwortmann** [comment]
While the relevant code has probably been rewritten several times since this issue was originally opened, I have just tested it with the setting `"show_diagnostics_severity_level": 0` and on my side this option completely removes all underline decorations in the file, warning/error icons in the gutter and also the diagnostic messages in the hover popup. So if it doesn't work on your side, I would consider that a bug. In that case ideally we would need a way to reproduce it.

From a quick look over the relevant code, I don't see any circumstances or reasons why it wouldn't work. The code responsible for drawing the icons and underlines is at
https://github.com/sublimelsp/LSP/blob/4a6dc060e01444412d172e404e99d31bfe1549cc/plugin/session_view.py#L326-L337
and here the `max_severity_level` variable in the if-condition corresponds to the mentioned user setting. This code should apply regardless whether the server uses the push diagnostics model or the newer pull diagnostics model from the LSP specs.

**Comment by sterliakov** [comment]
@jwortmann Okay, I'm feeling dumb now... :facepalm: Sorry for bumping the old thread. I tried this setting several years ago and it still didn't disable everything as I wanted. Somehow trying it again and expecting that this was fixed simply didn't come to my mind. Huge thanks, my battle with LSP servers diagnostics is now over!
